### PR TITLE
enhancement: sqlexec function support parameter inside cSQLCommand

### PR DESCRIPTION
**Pull request by jpmoschi**
the forum reference is 
https://www.xsharp.eu/forum/public-vfp/2560-sqlexec-parameters-input-output

FoxPro detect the parameter with the quotation character '?'
if the character followed is '@', It is an output parameter
if the character followed is '(', It is an VFP expression closed between  parenthesis

Tested only in MSSQLServer and ORACLE

the parameters can be private or public variables. there is a problem with parameter because then must be private variable inside a method, function or free procedure

### CODE REVIEW

**Comment by RobertvanderHulst** [comment]
Juan, I have merged this now. I'll review your code and will probably make some changes. I noticed that the code did not compile without warnings when integrated in the XSharp.VFP assembly.

One thing to clarify: I will restore the` [NeedsAccessToLocals(TRUE)]` attribute because this is needed for code such as the example from the SQLEXEC() topic in the FoxPro help file:

```
LOCAL lnOutput
.
.
SQLEXEC(m.lnConn, "exec #myProc2 ?lnPercent, ?@lnOutput")
```

As you can see lnOutput is declared as local, and to be able to set this local from within the SQLEXEC code we need to tell the compiler that locals should be "assignable" with the MemVarPut() syntax. The ` [NeedsAccessToLocals(TRUE)]` attribute tells the compiler to register the locals in a list so they can be accessed and also assigned (that is what the TRUE does) is for inside the SQLEXEC code. 
The result is that the compiler will insert code before the call to SQLEXEC() 
`
__LocalPut( <localvariablename>, localvariable); // for all local variables`

and the following code after the call to SqlExec()
```
if __LocalsUpdated()
     localvariable = __LocalGet( <localvariablename> ); // for all local variables
endif
```

**Comment by jpmoschi** [comment]
Thank you Robert for your time and effort
I understood your explanations and trying to reduce the extra cost of passing the local variables to the SqlExec function I ask you: is it possible to put the a conditional if before the insert code?  :
```
if < <2nd SqlExec parameter expression> >.Contains("@?")  
   __LocalPut( <localvariablename>, localvariable); // for all local variables
endif
```
Why? because when the procedures have many lines (ex 4000 lines) and several local variables, the transfer for each call can be expensive and in my experience there are many queries and few calls to stored procedures with output parameters
Please take this as a minor opinion because I have no idea of ​​the real cost of passing eg: the same 100 variables to 10 or 20 SqlExec() calls
Thank you again
Best regards

**Comment by RobertvanderHulst** [comment]
Juan,
The code in the compiler that takes care of the handling of the Locals does not know (at least not at this moment) what the function that is called does.
The attribute is also used for the macro compiler to make sure that an expression such as 
`&("mylocal = 42") 
`
will also update a local with that name.
And the cost (execution time) of these __LocalPut() can probably be neglected when compared to the cost of calling a stored procedure that runs code on another machine.

Recently we looked at the performance of our RDD system.  I expected that some algorithms could be improved. But that proved NOT to make much difference:  the biggest part of the execution time was in the Disk I/O. Removing a flush to disk did more than hundreds of hours of improving an algorithm could achieve.

**Comment by jpmoschi** [comment]
Good morning, Robert, I detected an error in the tests passing a parameter with a null value. I Fixed it and I took the opportunity to correct the warnings you mentioned. How do you prefer me to proceed to incorporate the changes?

**Comment by RobertvanderHulst** [comment]
Juan,
Commit the changes in your own repo and send a pull request

**Pull request merged**
