### PR TITLE
Adjustments to designer windows

### PR DESCRIPTION
**Pull request by christianschmid200272**
ControlOrder
Conversion of the ControlOrder window from a modal dialog to a normal window.

PropGrid
If you select several controls in the Designer, the values in the properties window remain with the first selected control; now the properties of the last selected control are always displayed.

VoWindowEditor
Conversion of the VOControlCreationOrderDlg window from a modal dialog to a normal window.
Hiding the toolbox and the properties window only when the designer cannot take focus and not as before when the designer loses focus.
If controls are inserted via copy and paste, they are no longer added somewhere in the ControlOrder but at the end.Issue 1508

### CODE REVIEW

**Comment by cpyrgas** [comment]
Christian, nice change about the selection of multiple controls! I had the impression that VO kept the first control as the "main" selection, but you are right, it uses the last one.

There's a small problem with the copy/paste of controls, the order of the new one goes to second to last, not to last, but that's a tiny problem and easy to fix.

About the control order dialog, may I ask why you prefer it to be non-modal? There are a few problems now, for example the dialog does not update when you add new controls and remains open even if you move to another file. Also if you close the window that it "belongs" to, again it remains open and then throws an exception dialog if you try to close it.

I'm also not sure about the change regarding the Properties and Toolbox windows, as they now remain open when you switch to another app than VS, they can get in the way when you try to select another file in the Solution explorer etc. In which circumstances was the old behavior causing you trouble?

**Comment by christianschmid200272** [comment]
Hello Chris,
I actually thought that the last changeset had solved the problem of the penultimate one when inserting controls? Calling SELF:ArrangeControlOrder() again before the end of SELF:EndAction() fixed the problem for me.

**(See the lines with the angle brackets.)**

```
    VIRTUAL METHOD Paste() AS VOID
        LOCAL oEntry AS DesignerClipboardEntry
        LOCAL lNameConflict AS LOGIC
        LOCAL cGuid AS STRING
        LOCAL n,m, neworder AS INT

        IF SELF:lReadOnly
            RETURN
        ENDIF

        IF SELF:ViewMode == ViewMode.Browse .AND. SELF:eCopyMode != ViewMode.Browse
            RETURN
        END IF
        IF SELF:ViewMode != ViewMode.Browse .AND. SELF:eCopyMode == ViewMode.Browse
            RETURN
        END IF

        SELF:BeginAction()
        SELF:DoAction(DesignerActionType.DeSelectAll)

      >>>>>>>>>>>>>>>   neworder := SELF:ArrangeControlOrder():Count  <<<<<<<<<<<<<<<

        FOR n := 0 UPTO Clipboard:Count - 1
            oEntry := Clipboard:GetEntry(n)
            lNameConflict := SELF:NameExists(oEntry:cName)
            oEntry:nPasted ++
            cGuid := Guid.NewGuid():ToString()

            SELF:StartAction(DesignerBasicActionType.Create , ActionData{cGuid , oEntry:cClass , ""})

            FOR m := 0 UPTO oEntry:aProperties:Count - 1
                SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , oEntry:aProperties:GetName(m) , oEntry:aProperties:GetValue(m)})
            NEXT

            IF lNameConflict
                SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , "Name" , SELF:GetNextName(oEntry:cName)})
            END IF
            SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , "_Left" , oEntry:x + XCustomEditorSettings.PasteOffSetX * oEntry:nPasted})
            SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , "_Top" , oEntry:y + XCustomEditorSettings.PasteOffSetY * oEntry:nPasted})
            //set the order to end
            >>>>>>>>>>>>>>>SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , "__Order" ,  neworder++})<<<<<<<<<<<<<<<
            IF SELF:ViewMode == ViewMode.Browse
                SELF:StartAction(DesignerBasicActionType.SetProperty , ActionData{cGuid , "_Deleted" , 1})
            END IF
            SELF:DoAction(DesignerActionType.SelectAdd , cGuid)
        NEXT
        >>>>>>>>>>>>>>>SELF:ArrangeControlOrder()<<<<<<<<<<<<<<<
        SELF:EndAction()
        RETURN

```
Regarding the modal dialog of the ControlOrder, the problem is that we have very large windows with a lot of controls on them. If you have already selected a lot of controls when setting the order and suddenly realize that not all controls that you have to select are visible or are somehow hidden, you cannot scroll in the Designer in a modal dialog to fix this and always start from the beginning. We have been working with this change for quite some time without any problems, there are more problems when the dialog is modal.

**Comment by cpyrgas** [comment]
Hi Christian,

Hmm, I don't see the change regarding SELF:ArrangeControlOrder(), and seems it did not make it to the internal build we are testing. But it's easier to fix this, you just need to increase the neworder local before you use it to change the order, not after. I have adjusted that now.

OK, I understand about the modal ControlOrder. But unfortunately now there are some problems that do not affect you the way you work with it, but may affect others who work differently:

- It does not update when you add/remove controls
- It stays visible on top even if you switch to another tool
- If you close the VOWED that opened it, it remains open and "orphan". If you try to close it afterwards, an exception dialog is thrown

When you say that you have already selected a lot of controls and then need to scroll the screen, I assume you mean you are using the "Use mouse" functionality, is that correct? Recently I got a feature request also for XIDE, to make it possible to "Use Mouse" starting setting the order not from the beginning, but after a given control in the order, I assume for the exact same reason. Would this solution fix the underlying problem the way you work, too, without a need for a modeless control order dialog?

**Comment by christianschmid200272** [comment]
Hi Chris,
Yes, we use the “Use mouse” function. The possibility to set the order from a certain control should also solve the problem so that the dialog can be modal again. The best solution would be that the dialog is not modally bound to the currently open editor, but I haven't found a solution for that.

**Comment by cpyrgas** [comment]
Hi Christian,

OK, I have already implemented that solution and it seems to work well, but will also send you (by private email) our current beta installer, so you can give it a test as well, before it is released.

I agree, it would be ideal to make the dialog non modal and take care of the related problems, but since this is complicated, we can look into this again afterwards. Maybe it can be made an optional feature.

**Pull request merged**
